# Generated by Django 3.2.5 on 2021-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
