# Generated by Django 3.2.5 on 2021-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIADocuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docclass',
            name='date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
