# Generated by Django 3.2.4 on 2021-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('No', models.CharField(max_length=200)),
                ('Car', models.CharField(max_length=200)),
                ('Abbr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QaulyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos', models.IntegerField(default=0)),
                ('No', models.CharField(max_length=200)),
                ('Driver', models.CharField(max_length=200)),
                ('Car', models.CharField(max_length=200)),
                ('Q1', models.CharField(max_length=200)),
                ('Q2', models.CharField(max_length=200)),
                ('Q3', models.CharField(max_length=200)),
                ('Laps', models.IntegerField(default=0)),
                ('GP', models.CharField(max_length=200)),
            ],
        ),
    ]
