# Generated by Django 3.2.4 on 2021-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Head2Head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverclass',
            name='img',
            field=models.CharField(default='33', max_length=200),
        ),
    ]
