# Generated by Django 3.2.5 on 2021-07-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Head2Head', '0004_auto_20210710_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos', models.CharField(max_length=200)),
                ('No', models.CharField(max_length=200)),
                ('Driver', models.CharField(max_length=200)),
                ('Car', models.CharField(max_length=200)),
                ('Laps', models.IntegerField(default=0)),
                ('Time', models.CharField(max_length=200)),
                ('Pts', models.IntegerField(default=0)),
                ('GP', models.CharField(max_length=200)),
            ],
        ),
    ]
