# Generated by Django 3.2.5 on 2021-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Head2Head', '0005_sprintclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaulyclass',
            name='Pos',
            field=models.CharField(max_length=200),
        ),
    ]
