# Generated by Django 3.2.5 on 2021-08-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Head2Head', '0006_alter_qaulyclass_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitstopClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stops', models.IntegerField(default=0)),
                ('No', models.CharField(max_length=200)),
                ('Driver', models.CharField(max_length=200)),
                ('Total', models.CharField(max_length=200)),
                ('Time', models.CharField(max_length=200)),
                ('TOD', models.CharField(max_length=200)),
                ('Car', models.CharField(max_length=200)),
                ('Lap', models.IntegerField(default=0)),
                ('GP', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pos', models.CharField(max_length=200)),
                ('No', models.CharField(max_length=200)),
                ('Driver', models.CharField(max_length=200)),
                ('Car', models.CharField(max_length=200)),
                ('Laps', models.IntegerField(default=0)),
                ('Session', models.CharField(max_length=2)),
                ('Time', models.CharField(max_length=200)),
                ('GP', models.CharField(max_length=200)),
            ],
        ),
    ]
