# Generated by Django 3.2.5 on 2021-09-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Head2Head', '0007_pitstopclass_practiceclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultclass',
            name='Pts',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sprintclass',
            name='Pts',
            field=models.FloatField(default=0),
        ),
    ]
